# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rares655/test_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rares655/test_project/build

# Include any dependencies generated for this target.
include CMakeFiles/anotherName.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/anotherName.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/anotherName.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/anotherName.dir/flags.make

CMakeFiles/anotherName.dir/main.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/main.cpp.o: /home/rares655/test_project/main.cpp
CMakeFiles/anotherName.dir/main.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/anotherName.dir/main.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/main.cpp.o -MF CMakeFiles/anotherName.dir/main.cpp.o.d -o CMakeFiles/anotherName.dir/main.cpp.o -c /home/rares655/test_project/main.cpp

CMakeFiles/anotherName.dir/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/main.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/main.cpp > CMakeFiles/anotherName.dir/main.cpp.i

CMakeFiles/anotherName.dir/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/main.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/main.cpp -o CMakeFiles/anotherName.dir/main.cpp.s

CMakeFiles/anotherName.dir/discretization.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/discretization.cpp.o: /home/rares655/test_project/discretization.cpp
CMakeFiles/anotherName.dir/discretization.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/anotherName.dir/discretization.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/discretization.cpp.o -MF CMakeFiles/anotherName.dir/discretization.cpp.o.d -o CMakeFiles/anotherName.dir/discretization.cpp.o -c /home/rares655/test_project/discretization.cpp

CMakeFiles/anotherName.dir/discretization.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/discretization.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/discretization.cpp > CMakeFiles/anotherName.dir/discretization.cpp.i

CMakeFiles/anotherName.dir/discretization.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/discretization.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/discretization.cpp -o CMakeFiles/anotherName.dir/discretization.cpp.s

CMakeFiles/anotherName.dir/dijkstra.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/dijkstra.cpp.o: /home/rares655/test_project/dijkstra.cpp
CMakeFiles/anotherName.dir/dijkstra.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/anotherName.dir/dijkstra.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/dijkstra.cpp.o -MF CMakeFiles/anotherName.dir/dijkstra.cpp.o.d -o CMakeFiles/anotherName.dir/dijkstra.cpp.o -c /home/rares655/test_project/dijkstra.cpp

CMakeFiles/anotherName.dir/dijkstra.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/dijkstra.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/dijkstra.cpp > CMakeFiles/anotherName.dir/dijkstra.cpp.i

CMakeFiles/anotherName.dir/dijkstra.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/dijkstra.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/dijkstra.cpp -o CMakeFiles/anotherName.dir/dijkstra.cpp.s

CMakeFiles/anotherName.dir/read_points.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/read_points.cpp.o: /home/rares655/test_project/read_points.cpp
CMakeFiles/anotherName.dir/read_points.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/anotherName.dir/read_points.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/read_points.cpp.o -MF CMakeFiles/anotherName.dir/read_points.cpp.o.d -o CMakeFiles/anotherName.dir/read_points.cpp.o -c /home/rares655/test_project/read_points.cpp

CMakeFiles/anotherName.dir/read_points.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/read_points.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/read_points.cpp > CMakeFiles/anotherName.dir/read_points.cpp.i

CMakeFiles/anotherName.dir/read_points.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/read_points.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/read_points.cpp -o CMakeFiles/anotherName.dir/read_points.cpp.s

CMakeFiles/anotherName.dir/delaunay_trig.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/delaunay_trig.cpp.o: /home/rares655/test_project/delaunay_trig.cpp
CMakeFiles/anotherName.dir/delaunay_trig.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Building CXX object CMakeFiles/anotherName.dir/delaunay_trig.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/delaunay_trig.cpp.o -MF CMakeFiles/anotherName.dir/delaunay_trig.cpp.o.d -o CMakeFiles/anotherName.dir/delaunay_trig.cpp.o -c /home/rares655/test_project/delaunay_trig.cpp

CMakeFiles/anotherName.dir/delaunay_trig.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/delaunay_trig.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/delaunay_trig.cpp > CMakeFiles/anotherName.dir/delaunay_trig.cpp.i

CMakeFiles/anotherName.dir/delaunay_trig.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/delaunay_trig.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/delaunay_trig.cpp -o CMakeFiles/anotherName.dir/delaunay_trig.cpp.s

CMakeFiles/anotherName.dir/Astar.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/Astar.cpp.o: /home/rares655/test_project/Astar.cpp
CMakeFiles/anotherName.dir/Astar.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_6) "Building CXX object CMakeFiles/anotherName.dir/Astar.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/Astar.cpp.o -MF CMakeFiles/anotherName.dir/Astar.cpp.o.d -o CMakeFiles/anotherName.dir/Astar.cpp.o -c /home/rares655/test_project/Astar.cpp

CMakeFiles/anotherName.dir/Astar.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/Astar.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/Astar.cpp > CMakeFiles/anotherName.dir/Astar.cpp.i

CMakeFiles/anotherName.dir/Astar.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/Astar.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/Astar.cpp -o CMakeFiles/anotherName.dir/Astar.cpp.s

CMakeFiles/anotherName.dir/experimentPart.cpp.o: CMakeFiles/anotherName.dir/flags.make
CMakeFiles/anotherName.dir/experimentPart.cpp.o: /home/rares655/test_project/experimentPart.cpp
CMakeFiles/anotherName.dir/experimentPart.cpp.o: CMakeFiles/anotherName.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_7) "Building CXX object CMakeFiles/anotherName.dir/experimentPart.cpp.o"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/anotherName.dir/experimentPart.cpp.o -MF CMakeFiles/anotherName.dir/experimentPart.cpp.o.d -o CMakeFiles/anotherName.dir/experimentPart.cpp.o -c /home/rares655/test_project/experimentPart.cpp

CMakeFiles/anotherName.dir/experimentPart.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/anotherName.dir/experimentPart.cpp.i"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/rares655/test_project/experimentPart.cpp > CMakeFiles/anotherName.dir/experimentPart.cpp.i

CMakeFiles/anotherName.dir/experimentPart.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/anotherName.dir/experimentPart.cpp.s"
	/usr/bin/g++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/rares655/test_project/experimentPart.cpp -o CMakeFiles/anotherName.dir/experimentPart.cpp.s

# Object files for target anotherName
anotherName_OBJECTS = \
"CMakeFiles/anotherName.dir/main.cpp.o" \
"CMakeFiles/anotherName.dir/discretization.cpp.o" \
"CMakeFiles/anotherName.dir/dijkstra.cpp.o" \
"CMakeFiles/anotherName.dir/read_points.cpp.o" \
"CMakeFiles/anotherName.dir/delaunay_trig.cpp.o" \
"CMakeFiles/anotherName.dir/Astar.cpp.o" \
"CMakeFiles/anotherName.dir/experimentPart.cpp.o"

# External object files for target anotherName
anotherName_EXTERNAL_OBJECTS =

anotherName: CMakeFiles/anotherName.dir/main.cpp.o
anotherName: CMakeFiles/anotherName.dir/discretization.cpp.o
anotherName: CMakeFiles/anotherName.dir/dijkstra.cpp.o
anotherName: CMakeFiles/anotherName.dir/read_points.cpp.o
anotherName: CMakeFiles/anotherName.dir/delaunay_trig.cpp.o
anotherName: CMakeFiles/anotherName.dir/Astar.cpp.o
anotherName: CMakeFiles/anotherName.dir/experimentPart.cpp.o
anotherName: CMakeFiles/anotherName.dir/build.make
anotherName: /usr/lib/x86_64-linux-gnu/libgmpxx.so
anotherName: /usr/lib/x86_64-linux-gnu/libmpfr.so
anotherName: /usr/lib/x86_64-linux-gnu/libgmp.so
anotherName: CMakeFiles/anotherName.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=/home/rares655/test_project/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_8) "Linking CXX executable anotherName"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/anotherName.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/anotherName.dir/build: anotherName
.PHONY : CMakeFiles/anotherName.dir/build

CMakeFiles/anotherName.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/anotherName.dir/cmake_clean.cmake
.PHONY : CMakeFiles/anotherName.dir/clean

CMakeFiles/anotherName.dir/depend:
	cd /home/rares655/test_project/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/rares655/test_project /home/rares655/test_project /home/rares655/test_project/build /home/rares655/test_project/build /home/rares655/test_project/build/CMakeFiles/anotherName.dir/DependInfo.cmake "--color=$(COLOR)"
.PHONY : CMakeFiles/anotherName.dir/depend

