# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# compile CXX with /usr/bin/g++
CXX_DEFINES = -DCGAL_USE_GMPXX=1

CXX_INCLUDES = -isystem /home/rares655/cgal/CGAL-5.6.2/include

CXX_FLAGS = -frounding-math

